/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: "var(--color-primary)",
          light:   "var(--color-primary-light)",
          dark:    "var(--color-primary-dark)",
          deeper:  "var(--color-primary-deeper)",
        },
        background: "var(--color-bg)",
        secondary:  "var(--color-surface)",
        surface:    "var(--color-surface)",
        section:    "var(--color-section)",
        blush:      "var(--color-surface)",
        warm:       "var(--color-bg)",
        ink:        "var(--color-text-primary)",
        muted:      "var(--color-text-muted)",
        subtle:     "var(--color-text-secondary)",
        line:       "var(--color-border)",
        success:    "var(--color-success)",
        warning:    "var(--color-warning)",
        error:      "var(--color-error)",
      },
      fontFamily: {
        sans:  ["Poppins", "sans-serif"],
        serif: ["Cormorant Garamond", "serif"],
      },
      maxWidth: {
        content: "1440px",
      },
      borderRadius: {
        DEFAULT:    "20px",
        card:       "24px",
        "card-sm":  "18px",
        image:      "22px",
        input:      "16px",
        pill:       "9999px",
        hero:       "32px",
        "hero-lg":  "40px",
      },
      boxShadow: {
        xs:          "var(--shadow-xs)",
        soft:        "var(--shadow-soft)",
        card:        "var(--shadow-card)",
        "card-hover":"var(--shadow-card-hover)",
        lift:        "var(--shadow-lift)",
        hero:        "var(--shadow-hero)",
        float:       "var(--shadow-float)",
        glow:        "var(--shadow-glow)",
        "glow-sm":   "var(--shadow-glow-sm)",
        "inner-top": "inset 0 1px 0 var(--color-border)",
        "drawer":    "var(--shadow-drawer)",
      },
      spacing: {
        18:           "72px",
        22:           "88px",
        section:      "136px",
        "section-sm": "88px",
        inner:        "32px",
        card:         "24px",
      },
      letterSpacing: {
        tighter2: "-0.032em",
        tighter1: "-0.016em",
        tight1:   "-0.008em",
        wide1:    "0.05em",
        wide2:    "0.09em",
        wide3:    "0.18em",
      },
      lineHeight: {
        hero:    "1.05",
        heading: "1.12",
        snug1:   "1.28",
        relaxed: "1.82",
      },
      transitionTimingFunction: {
        premium: "cubic-bezier(0.22, 1, 0.36, 1)",
        spring:  "cubic-bezier(0.34, 1.56, 0.64, 1)",
        smooth:  "cubic-bezier(0.37, 0, 0.63, 1)",
      },
      transitionDuration: {
        250: "250ms",
        350: "350ms",
        400: "400ms",
        450: "450ms",
        600: "600ms",
        800: "800ms",
      },
      keyframes: {
        floaty: {
          "0%,100%": { transform: "translateY(0px) rotate(0deg)" },
          "40%":     { transform: "translateY(-20px) rotate(3.5deg)" },
          "70%":     { transform: "translateY(-9px) rotate(-1.5deg)" },
        },
        floatySlow: {
          "0%,100%": { transform: "translateY(0px) rotate(0deg)" },
          "50%":     { transform: "translateY(-13px) rotate(2deg)" },
        },
        shimmer: {
          "0%":   { backgroundPosition: "-600px 0" },
          "100%": { backgroundPosition:  "600px 0" },
        },
        shimmerSlide: {
          "0%":   { transform: "translateX(-100%)" },
          "100%": { transform: "translateX(100%)" },
        },
        blobMorph: {
          "0%,100%": { borderRadius: "60% 40% 30% 70% / 60% 30% 70% 40%" },
          "33%":     { borderRadius: "30% 60% 70% 40% / 50% 60% 30% 60%" },
          "66%":     { borderRadius: "50% 50% 30% 70% / 40% 60% 40% 60%" },
        },
        spinSlow: {
          from: { transform: "rotate(0deg)"   },
          to:   { transform: "rotate(360deg)" },
        },
      },
      animation: {
        floaty:      "floaty 6.5s ease-in-out infinite",
        floatySlow:  "floatySlow 9s ease-in-out infinite",
        shimmer:     "shimmer 1.8s linear infinite",
        shimmerSlide:"shimmerSlide 1.5s ease-in-out infinite",
        blobMorph:   "blobMorph 14s ease-in-out infinite",
        "spin-slow": "spinSlow 30s linear infinite",
      },
    },
  },
  plugins: [],
};
